Migrate registry/strategy Updates to webhooks
kyma-incubator/service-catalog pull request #17
Opened 2019-04-08 07:17 UTC by piotrmiskiewicz

This PR is a 
 - [ ] Feature Implementation
 - [ ] Bug Fix
 - [ ] Documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** 

Fixes #

Please leave this checklist in the PR comment so that maintainers can ensure a good PR.

Merge Checklist:
 - [ ] New feature 
   - [ ] Tests
   - [ ] Documentation
 - [ ] SVCat CLI flag
 - [ ] Server Flag for config
   - [ ] Chart changes
   - [ ] removing a flag by marking deprecated and hiding to avoid
         breaking the chart release and existing clients who provide a
         flag that will get an error when they try to update

2019-04-08 07:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kyma-incubator/service-catalog?pullRequest=17) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kyma-incubator/service-catalog?pullRequest=17) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kyma-incubator/service-catalog?pullRequest=17) it.</sub>

2019-04-11 11:23 UTC, mszostok requested changes
In issue that you want to resolve is such comment
>For validation take into account that we have already the static validation on CRD, so recheck what else needs to be done in ValidatingAdmissionWebhook.
>
>Check also if we shouldn't remove the static validation from CRD and implement that in ValidatingAdmissionWebhook - take into account how user-friendly is the returned validation error.

Why in your pr it's not done? Right now we have duplicated logic, also the err msgs are not validated and I do not see any statement which approach was chosen and why. Base on my testing we should remove validation from CRDs


What's more right now you have registered validation which cannot work:
- ServiceBinding (ValidateServiceBinding), under the hood, is doing:
```
	if create {
		allErrs = append(allErrs, validateServiceBindingCreate(binding)...)
	} else {
		allErrs = append(allErrs, validateServiceBindingUpdate(binding)...)
	}
```
both operation are validating status which is not provided on normal CREATE operation for ServiceBinding and **it will not work.**. Checking must be moved to status update handler. _Validation for creating is not needed because user is not able to do that._
- ServiceInstance (ValidateServiceInstanceUpdate), under the hood is validating the status entry, why it's not registered in webhook??

2019-04-11 11:23 UTC, mszostok commented on pkg/apis/servicecatalog/v1beta1/validation/binding.go
> +/*
as discussed. We can remove this copy and just adjust the imports in previous package.

2019-04-11 11:23 UTC, mszostok commented on pkg/webhook/servicecatalog/clusterservicebroker/mutation/handler.go
> +			traced.Errorf("Could not decode request object: %v", err)
be more verbose, right now we cannot distinguish if it was problem with oldObj or req.Obj (line 59)

**same comment for all other places**

2019-04-11 11:23 UTC, mszostok commented on pkg/webhook/servicecatalog/clusterservicebroker/mutation/handler.go
> +func (h *CreateUpdateHandler) mutateOnUpdate(ctx context.Context, oldSb, newSb *sc.ClusterServiceBroker) {
minior: sometimes you are using `originalObj` sometimes `oldSb`, please unify that

**same comment for all other places**

2019-04-11 11:23 UTC, mszostok commented on pkg/webhook/servicecatalog/clusterservicebroker/mutation/handler.go
> +	if !apiequality.Semantic.DeepEqual(oldSb.Spec, newSb.Spec) {
did you check that behavior previously? In the webhook approach, this is not needed at all. **Please remove that.**

**same comment for all other places**

2019-04-11 11:23 UTC, mszostok commented on pkg/webhook/servicecatalog/clusterservicebroker/mutation/handler_test.go
> +		"Should override relist request": {
```suggestion
		"Should restore previous relist request, when not provided (set to 0)": {
```

2019-04-11 11:23 UTC, mszostok commented on pkg/webhook/servicecatalog/clusterservicebroker/validation/clusterservicebroker_validator.go
> +/*
why this file is called `clusterservicebroker_validator.go` ??
You are already in `clusterservicebroker/validation` pkg

please name it by its behaviour, e.g. static validation, basic validation, spec validation etc.

2019-04-11 11:23 UTC, mszostok commented on pkg/webhook/servicecatalog/clusterservicebroker/mutation/handler.go
> +	// This feature was copied from Service Catalog registry: https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/registry/servicecatalog/clusterservicebroker/strategy.go
this comment is not needed here. The purpose of this comment is to have it in places where you copied a lot of logic, e.g. as you had for validation packages. In this place is more like adjustments because some logic is not ported e.g. as we have with recovering status entries, incrementing generation etc.

2019-04-11 11:23 UTC, mszostok commented on pkg/webhook/servicecatalog/clusterservicebroker/mutation/handler_test.go
> +		"Should update ServiceBroker generation": {
This is done by main api server. This test case should be included in unit tests

2019-04-11 11:23 UTC, mszostok commented on pkg/webhook/servicecatalog/clusterservicebroker/validation/clusterservicebroker_validator.go
> +type ClusterServiceBrokerCreateValidator struct {
please name it by its behavior

as you can see such statement makes sense:
`CreateValidators: []Validator{&AccessToBroker{}},`

This one nope:
`CreateValidators: []Validator{&ClusterServiceBrokerCreateValidator{}},`


**Same suggestion for other validation structs that you created for other kinds**

2019-04-11 11:23 UTC, mszostok commented on pkg/webhook/servicecatalog/clusterservicebroker/mutation/handler.go
> +	if newSb.Spec.RelistRequests == 0 {
please revert this comment here
`// Ignore the RelistRequests field when it is the default value`

2019-04-11 11:23 UTC, mszostok commented on pkg/webhook/servicecatalog/clusterserviceclass/validation/handler.go
> +	traced.Infof("Start handling AdmissionHandler operation: %s for %s: %q", req.Operation, req.Kind.Kind, req.Name)
you have outdated log msg. With this log msg you cannot distinguish between validation and mutation
`traced.Infof("Start handling validation operation: %s for %s", req.Operation, req.Kind.Kind)`

**please adjust also other places.**

2019-04-11 11:23 UTC, mszostok commented on pkg/webhook/servicecatalog/servicebinding/mutation/handler.go
> +	resp := admission.PatchResponseFromRaw(req.AdmissionRequest.Object.Raw, rawMutated)
why not just return it as it was previously?

2019-04-11 11:23 UTC, mszostok commented on pkg/webhook/servicecatalog/servicebinding/mutation/handler.go
> +	// Fill in the first entry set to "creating"?
this comment is not needed here

2019-04-11 11:23 UTC, mszostok commented on pkg/webhook/servicecatalog/servicebinding/mutation/handler.go
> +	// This feature was copied from Service Catalog registry: https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/registry/servicecatalog/binding/strategy.go
this comment is not needed here. The purpose of this comment is to have it in places where you copied a lot of logic, e.g. as you had for validation packages. In this place is more like adjustments because some logic is not ported e.g. as we have with recovering status entries, incrementing generation etc.

2019-04-11 11:23 UTC, mszostok commented on pkg/webhook/servicecatalog/servicebinding/mutation/handler.go
> +		newObj.Generation = oldObj.Generation + 1
please remove it is done by api server

2019-04-11 11:23 UTC, mszostok commented on pkg/webhook/servicecatalog/serviceinstance/mutation/handler.go
> +	traced.Infof("subresource %v", req.SubResource)
should it still be here?

2019-04-11 11:23 UTC, mszostok commented on pkg/webhook/servicecatalog/servicebroker/validation/handler_status.go
> +	traced.Infof("Start handling operation: %s for %s/%s: %q", req.Operation, req.Kind.Kind, req.SubResource, req.Name)
please be  more precise. What kind of handler it is? It' will be hard to distinguish between validation sepc,  mutation spec, and mutation status entries

2019-04-12 08:36 UTC, piotrmiskiewicz commented on pkg/apis/servicecatalog/v1beta1/validation/binding.go
> +/*
removed the package and modified the old one (to use proper types/imports which makes API Server version not workig as discussed)

2019-04-12 10:38 UTC, piotrmiskiewicz commented on pkg/webhook/servicecatalog/clusterservicebroker/mutation/handler.go
> +			traced.Errorf("Could not decode request object: %v", err)
log message changed

2019-04-12 10:38 UTC, piotrmiskiewicz commented on pkg/webhook/servicecatalog/clusterservicebroker/mutation/handler.go
> +func (h *CreateUpdateHandler) mutateOnUpdate(ctx context.Context, oldSb, newSb *sc.ClusterServiceBroker) {
unified

2019-04-12 10:39 UTC, piotrmiskiewicz commented on pkg/webhook/servicecatalog/clusterservicebroker/mutation/handler.go
> +	if !apiequality.Semantic.DeepEqual(oldSb.Spec, newSb.Spec) {
removed

2019-04-12 10:39 UTC, piotrmiskiewicz commented on pkg/webhook/servicecatalog/clusterservicebroker/mutation/handler_test.go
> +		"Should override relist request": {
fixed

2019-04-12 10:39 UTC, piotrmiskiewicz commented on pkg/webhook/servicecatalog/servicebinding/mutation/handler.go
> +	// Fill in the first entry set to "creating"?
removed

2019-04-12 10:40 UTC, piotrmiskiewicz commented on pkg/webhook/servicecatalog/servicebinding/mutation/handler.go
> +	// This feature was copied from Service Catalog registry: https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/registry/servicecatalog/binding/strategy.go
fixed

2019-04-12 10:40 UTC, piotrmiskiewicz commented on pkg/webhook/servicecatalog/serviceinstance/mutation/handler.go
> +	traced.Infof("subresource %v", req.SubResource)
no, I forgot to remove it. fixed

2019-04-12 10:40 UTC, piotrmiskiewicz commented on pkg/webhook/servicecatalog/servicebroker/validation/handler_status.go
> +	traced.Infof("Start handling operation: %s for %s/%s: %q", req.Operation, req.Kind.Kind, req.SubResource, req.Name)
enhanced message

2019-04-12 10:41 UTC, piotrmiskiewicz commented on pkg/webhook/servicecatalog/clusterservicebroker/validation/clusterservicebroker_validator.go
> +/*
renatmed to static.go

2019-04-12 10:42 UTC, piotrmiskiewicz commented on pkg/webhook/servicecatalog/clusterservicebroker/mutation/handler.go
> +	// This feature was copied from Service Catalog registry: https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/registry/servicecatalog/clusterservicebroker/strategy.go
comment removed

2019-04-12 11:36 UTC, piotrmiskiewicz commented on pkg/webhook/servicecatalog/clusterservicebroker/mutation/handler_test.go
> +		"Should update ServiceBroker generation": {
removed

2019-04-12 11:43 UTC, piotrmiskiewicz commented on pkg/webhook/servicecatalog/clusterservicebroker/validation/clusterservicebroker_validator.go
> +type ClusterServiceBrokerCreateValidator struct {
changed to StaticUpdate and StaticCreate

2019-04-12 11:45 UTC, piotrmiskiewicz commented on pkg/webhook/servicecatalog/clusterservicebroker/mutation/handler.go
> +	if newSb.Spec.RelistRequests == 0 {
done

2019-04-12 11:49 UTC, piotrmiskiewicz commented on pkg/webhook/servicecatalog/clusterserviceclass/validation/handler.go
> +	traced.Infof("Start handling AdmissionHandler operation: %s for %s: %q", req.Operation, req.Kind.Kind, req.Name)
fixed

2019-04-12 11:50 UTC, piotrmiskiewicz commented on pkg/webhook/servicecatalog/servicebinding/mutation/handler.go
> +	resp := admission.PatchResponseFromRaw(req.AdmissionRequest.Object.Raw, rawMutated)
fixed

2019-04-12 11:50 UTC, piotrmiskiewicz commented on pkg/webhook/servicecatalog/servicebinding/mutation/handler.go
> +		newObj.Generation = oldObj.Generation + 1
removed

2019-04-16 06:07 UTC, adamwalach commented on charts/catalog/values.yaml
> +      securePort: 30444
Why the securePort was changed?

2019-04-16 08:34 UTC, adamwalach commented on pkg/webhook/servicecatalog/clusterserviceplan/mutation/handler.go
> +	traced.Infof("Start handling validation  operation: %s for %s: %q", req.Operation, req.Kind.Kind, req.Name)
should be "mutation" operation?

2019-04-16 11:30 UTC, piotrmiskiewicz commented on charts/catalog/values.yaml
> +      securePort: 30444
by accident, reverted

2019-04-16 11:34 UTC, mszostok approved these changes

2019-04-16 11:41 UTC, piotrmiskiewicz commented on pkg/webhook/servicecatalog/clusterserviceplan/mutation/handler.go
> +	traced.Infof("Start handling validation  operation: %s for %s: %q", req.Operation, req.Kind.Kind, req.Name)
fixed

2019-04-16 12:30 UTC, merged