Replace tableconvertor with APC
kyma-incubator/service-catalog pull request #20
Opened 2019-04-18 12:24 UTC by adamwalach

**Related issues**
* https://github.com/kyma-project/kyma/issues/2790

2019-04-23 06:32 UTC, mszostok reviewed
so far it looks good :)

2019-04-23 06:32 UTC, mszostok commented on pkg/controller/controller_instance.go
> +			// There has been an update to the instance. Start reconciliation
this comment does not look like being a proper one

2019-04-26 07:42 UTC, piotrmiskiewicz requested changes

2019-04-26 07:42 UTC, piotrmiskiewicz commented on pkg/controller/controller_servicebroker.go
> +	toUpdate.Status.LastConditionState = getServiceBrokerLastConditionState(toUpdate.Status.CommonServiceBrokerStatus)
is it tester somewhere? I've just commented the line and all unit tests are green

2019-04-26 07:42 UTC, piotrmiskiewicz commented on pkg/controller/controller_servicebroker.go
> +	toUpdate.Status.LastConditionState = getServiceBrokerLastConditionState(toUpdate.Status.CommonServiceBrokerStatus)
why do not put the update  LastConditionState to updateCommonStatusCondition function?

2019-04-26 12:52 UTC, piotrmiskiewicz approved these changes

2019-04-26 12:54 UTC, adamwalach commented on pkg/controller/controller_servicebroker.go
> +	toUpdate.Status.LastConditionState = getServiceBrokerLastConditionState(toUpdate.Status.CommonServiceBrokerStatus)
I added tests, and move the update to funtion

2019-04-29 09:10 UTC, merged