Pre delete jobs - remove CRD after delete helm release
kyma-incubator/service-catalog pull request #21
Opened 2019-05-06 08:58 UTC by jasiu001

Related to [#3763](https://github.com/kyma-project/kyma/issues/3763)
**Description**
Add `pre-delete` job for helm release which takes three steps
- scale down controller manager pod
- remove `service-catalog` finalizers from all CRs
- remove all CRDs with specific label

additionally there is readiness  probe for webhook server which checks all CRDs are install
(controller manager already has this kind of readiness probe)

2019-05-08 07:22 UTC, mszostok requested changes
where are tests both for the cleaner.go and finalizer_cleaner.go? This project is an open source where a lot of people will contribute, so at least we need to have basic unit coverage

2019-05-08 07:22 UTC, mszostok commented on cmd/cleaner/server/cleaner.go
> +	clr, err := cleaner.NewCleaner()
`cleaner.NewCleaner()` -> `cleaner.New()` we do not need to stutter

2019-05-08 07:22 UTC, mszostok commented on cmd/webhook/server/readiness_probe.go
> +		return &ReadinessCRD{}, err
```suggestion
		return nil, err
```

2019-05-08 07:22 UTC, mszostok commented on cmd/webhook/server/readiness_probe.go
> +	return &ReadinessCRD{apiextensionsClient, releaseName}, nil
is better to use always named params

```
return &ReadinessCRD{client: apiextensionsClient, release: releaseName}, nil
```

2019-05-08 07:22 UTC, mszostok commented on pkg/cleaner/cleaner.go
> +		return &Cleaner{}, fmt.Errorf("failed to get Kubernetes client config: %v", err)
```suggestion
		return nil, fmt.Errorf("failed to get Kubernetes client config: %v", err)
```

2019-05-08 07:22 UTC, mszostok commented on pkg/cleaner/cleaner.go
> +		return fmt.Errorf("failed to update deployment $s/%s: %v", namespace, controllerName, err)
```suggestion
		return fmt.Errorf("failed to update deployment %s/%s: %v", namespace, controllerName, err)
```

2019-05-08 07:22 UTC, mszostok commented on pkg/cleaner/cleaner.go
> +		podList, err := client.CoreV1().Pods(namespace).List(v1.ListOptions{LabelSelector: "app=" + controllerName})
shouldn't be better to check the deployment status and check if current&available is 0? 
```
 kyma/installation on (master) kubectl get deploy helm-broker
NAME          DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
helm-broker   0         0         0            0           3h28m
```

Reason:
Using the label selector is not on any contract but using the deployment name is ok, because it's parameter provided by user :)

2019-05-08 07:22 UTC, mszostok commented on pkg/cleaner/finalizer_cleaner.go
> +func removeFinalizer(finalizers sets.String) []string {
removeFinalizer -> removeServiceCatalogFinalizer 


what's more as an input you should accept the slice of string. Right now in each method you need to write additionally `(sets.NewString(plan.Finalizers...))` but it could be simply `removeServiceCatalogFinalizer(plan.Finalizers)`


I'm also considering if we should remove only Service Catalog finalizers or all? TBH I do not have the answer yet, so maybe leave some TODO in code with this question, what kind of approach should be used, or if you have a strong opinion on the given approach then we can discuss that

2019-05-08 07:22 UTC, mszostok commented on pkg/cleaner/finalizer_cleaner.go
> +			klog.V(4).Info("finalizezers not removed, retry...")
```suggestion
			klog.V(4).Info("finalizers not removed, retry...")
```

same typo in others funcs

2019-05-08 07:22 UTC, mszostok commented on pkg/cleaner/finalizer_cleaner.go
> +	list, err := client.ServicecatalogV1beta1().ServiceBrokers("").List(v1.ListOptions{})
```suggestion
	list, err := client.ServicecatalogV1beta1().ServiceBrokers(v1.NamespaceAll).List(v1.ListOptions{})
```

same of other places

2019-05-08 07:22 UTC, mszostok commented on pkg/cleaner/finalizer_cleaner.go
> +			return fmt.Errorf("failed while waiting for finalizarots will be removed: %s", err)
`finalizarots` ? :D

2019-05-08 07:22 UTC, mszostok commented on cmd/webhook/server/readiness_probe.go
> +func (r *ReadinessCRD) Check(_ *http.Request) error {
Discussed f2f

- please move that logic under the `/pkg` directory
- please check the status of the CRD (if it's accepted by the API Server)
- please use that approach both in webhook server and controller-manager

2019-05-08 07:22 UTC, mszostok commented on pkg/cleaner/cleaner.go
> +func (c *Cleaner) RemoveCRDs(releaseName, releaseNamespace, controllerManagerName string) error {
Discussed f2f:

1. Remove the CRD (for each execute Delete action)
2. Check if CRs still exits if yes then remove the Service Catalog finalizers 
2.1. Wait till all finalizers are removed
3. Check if all CRDs from Service Catalog were removed


benefit from removing the CRDs before CRs:
- User will not be able to add new CRs
  ```
  Error from server (MethodNotAllowed): error when creating "broker.yaml": the server does not allow this method on the requested resource (post clusterservicebrokers.servicecatalog.k8s.io)
  ```

2019-05-13 09:43 UTC, mszostok commented on pkg/cleaner/cleaner.go
> +// RemoveCRDs takes four steps, first scale down controller manager deployment, second removes all ServiceCatalog CRDs,
please split those step to new lines, it will be more readable

2019-05-13 09:43 UTC, mszostok commented on pkg/cleaner/cleaner.go
> +	deployment, err := c.client.
please inline that. It will be consistent with rest of your code, e.g. line 91, 98 etc.

2019-05-13 09:43 UTC, mszostok commented on pkg/cleaner/cleaner.go
> +Copyright 2017 The Kubernetes Authors.
please fix that header in each file. We should set the 2019 year :)

2019-05-13 09:43 UTC, mszostok commented on pkg/cleaner/cleaner.go
> +		return fmt.Errorf("CustomResourceDefinitions list is not empty. There are %d CRD(s)", amount)
maybe we can add also the name. The easiest way is to just replace the `amount` with slice `[]string` in which you will append name of the CRD that is still not removed

2019-05-13 09:43 UTC, mszostok commented on pkg/cleaner/cleaner_test.go
> +func newTestCRD() []runtime.Object {
```suggestion
func newTestCRDs() []runtime.Object {
```

2019-05-13 09:43 UTC, mszostok commented on pkg/cleaner/cleaner_test.go
> +	assert.Len(t, list.Items, 1)
can w also assert the name? then the comment above will not be necessary and code will be self-described

2019-05-13 09:43 UTC, mszostok commented on pkg/cleaner/finalizer_cleaner.go
> +		return fmt.Errorf("failed during removing ClusterServiceBroker finalizer: %s", err)
in Service Catalog there is a `pretty` maybe you can use it here for each statement and replace e.g. `ClusterServiceBroker` with `pretty.ClusterServiceBroker`

2019-05-13 09:43 UTC, mszostok commented on pkg/cleaner/finalizer_cleaner.go
> +type CRWithFinalizer interface {
```suggestion
type FinalizerGetter interface {
```

in go the interface name are generally named like, statusGetter, ReadCloser, xxxUpdateDeleter etc

2019-05-17 09:22 UTC, piotrmiskiewicz approved these changes
lgtm - works as expected

2019-05-17 09:27 UTC, mszostok commented on pkg/cleaner/cleaner.go
> +type Cleaner struct {
missing comment

2019-05-17 09:27 UTC, mszostok commented on pkg/cleaner/finalizer_cleaner.go
> +type FinalizerCleaner struct {
missing comment

2019-05-17 09:27 UTC, mszostok commented on pkg/cleaner/finalizer_cleaner.go
> +type FinalizerGetter interface {
missing comment

2019-05-17 09:27 UTC, mszostok commented on pkg/probe/readiness_probe.go
> +type ReadinessCRD struct {
missing comment

2019-05-17 09:46 UTC, mszostok approved these changes

2019-05-17 09:46 UTC, merged