Add migration job to chart
kyma-incubator/service-catalog pull request #31
Opened 2019-06-24 13:01 UTC by polskikiel

This PR is a 
 - [ ] Feature Implementation
 - [ ] Bug Fix
 - [ ] Documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** 

Fixes #

Please leave this checklist in the PR comment so that maintainers can ensure a good PR.

Merge Checklist:
 - [ ] New feature 
   - [ ] Tests
   - [ ] Documentation
 - [ ] SVCat CLI flag
 - [ ] Server Flag for config
   - [ ] Chart changes
   - [ ] removing a flag by marking deprecated and hiding to avoid
         breaking the chart release and existing clients who provide a
         flag that will get an error when they try to update

2019-06-25 09:47 UTC, klaudiagrz commented on docs/migration-apiserver-to-crds.md
> +| apiserver-deployment | Provides the Apiserver deployment name. It is required only for `backup` phase |
```suggestion
| apiserver-deployment | Provides the Apiserver deployment name. It is required only for the `backup` phase. |
```

2019-06-25 09:47 UTC, klaudiagrz commented on docs/migration-apiserver-to-crds.md
> +In case your migration job failed you can check its logs using the following commands:
```suggestion
In case your migration job failed, you can check its logs using the following command:
```

2019-06-25 09:47 UTC, klaudiagrz commented on docs/migration-apiserver-to-crds.md
> +### Troubleshooting
```suggestion
## Troubleshooting
```

2019-06-25 09:47 UTC, klaudiagrz commented on docs/migration-apiserver-to-crds.md
> +### Cleanup
```suggestion
## Cleanup
```

2019-06-25 09:47 UTC, klaudiagrz commented on docs/migration-apiserver-to-crds.md
> +You can delete all the migration related resources using this command:
```suggestion
You can delete all the migration-related resources using this command:
```

2019-06-25 09:47 UTC, klaudiagrz commented on docs/migration-apiserver-to-crds.md
> +### Cleanup
I'd move this section above the Troubleshooting.

2019-06-25 09:57 UTC, klaudiagrz requested changes

2019-06-25 09:57 UTC, klaudiagrz commented on docs/migration-apiserver-to-crds.md
> +### Cleanup
Now it looks as if Cleanup is a part of Troubleshooting. Please fix that.

2019-06-25 10:04 UTC, polskikiel commented on docs/migration-apiserver-to-crds.md
> +### Cleanup
```suggestion
## Cleanup
```

2019-06-25 10:41 UTC, klaudiagrz approved these changes

2019-06-26 06:23 UTC, jasiu001 commented on charts/catalog/templates/migration-job.yaml
> +    "helm.sh/hook-delete-policy": before-hook-creation
What is the reason you do not use `hook-succeeded` policy for all resources?

2019-06-26 06:32 UTC, jasiu001 commented on pkg/migration/migration.go
> +}
imo the error type should be check to be sure error is about "not found" issue or other problems

```
import "k8s.io/apimachinery/pkg/api/errors"
(...)
if errors.IsNotFound(err) {
	return false, nil
}
if err != nil {
	return false, fmt.Errorf("other type of error: %s", err)
}
```

2019-06-26 08:48 UTC, jasiu001 approved these changes

2019-06-26 12:21 UTC, merged